# Generated by Django 5.0.6 on 2024-08-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='GameModel',
        ),
    ]
