# Generated by Django 5.0.6 on 2024-08-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0002_rename_game_gamemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
