# Generated by Django 5.0.6 on 2024-08-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='medias/images/'),
        ),
    ]
