# Generated by Django 5.0.6 on 2024-08-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0005_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
