# Generated by Django 5.0.6 on 2024-08-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0007_gamemodel_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='player1',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player2',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
