# Generated by Django 5.0.6 on 2024-08-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0008_alter_gamemodel_player1_alter_gamemodel_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='player1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
