# Generated by Django 5.0.6 on 2024-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0010_gamemodel_player1_ready_gamemodel_player2_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='player1_ready',
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='player2_ready',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='in_game_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
