# Generated by Django 5.0.6 on 2024-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0012_alter_gamemodel_in_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='player1_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='player2_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
