# Generated by Django 5.0.6 on 2024-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0013_gamemodel_player1_text_gamemodel_player2_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='player1_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player2_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
