# Generated by Django 5.0.6 on 2024-08-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0014_alter_gamemodel_player1_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='note',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='player1_note',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='player2_note',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
