# Generated by Django 5.0.6 on 2024-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0019_alter_gamemodel_player1_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
