# Generated by Django 5.0.6 on 2024-08-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0020_gamemodel_player1_ready_gamemodel_player2_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
