# Generated by Django 5.0.6 on 2024-08-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findapp', '0022_bugmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='player1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='player2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
